const REQUEST_ARTICLES = 'REQUEST_ARTICLES';
const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES';
const RECEIVE_MORE_ARTICLES = 'RECEIVE_MORE_ARTICLES';
const REQUEST_SOURCES = 'REQUEST_SOURCES';
const RECEIVE_SOURCES = 'RECEIVE_SOURCES';
const SET_API_ERROR = 'SET_API_ERROR';

export default {
  REQUEST_ARTICLES,
  RECEIVE_ARTICLES,
  RECEIVE_MORE_ARTICLES,
  REQUEST_SOURCES,
  RECEIVE_SOURCES,
  SET_API_ERROR,
};
